QuanLyMamNon/QuanLyMamNon/Areas/Admin/Controllers/KeToanController.cs
using QuanLyMamNon.Common;
using QuanLyMamNon.Models;
using QuanLyMamNon.Models.Dao;
using QuanLyMamNon.Reponsitory;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace QuanLyMamNon.Areas.Admin.Controllers
{
    [AuthorizeController]
    public class KeToanController : Controller
    {
        // GET: Admin/KeToan
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult DanhSachHocSinh(string groupLop)
        {
            try
            {

            HocSinhReponsitory HsRepon = new HocSinhReponsitory();
            LopReponsitory lopRepon = new LopReponsitory();
            var lstHS = new List<HocSinh>();
            if (groupLop == null || groupLop.Equals("0"))
            {
                groupLop = "0";
                lstHS = HsRepon.GetAllHocSinh();
            }
            else
            {
                lstHS = HsRepon.GetHocSinhForIdLop(groupLop);
            }
            ViewBag.select = groupLop;
            var viewModel = new ViewModelDanhSachHS
            {
                listLop = lopRepon.getAllLop(),
                listHocSinh = lstHS
            };
            return View(viewModel);
            }
            catch (Exception ex)
            {
                return RedirectToAction("SystemError", "Login");
            }
        }

        public ActionResult HocPhiHocSinh(string MaHocSinh)
        {
            try
            {

            PhieuThuHocPhiReponsitory ptRepon = new PhieuThuHocPhiReponsitory();
            HocSinhReponsitory hsRepon = new HocSinhReponsitory();
            HocSinh hocSinh = hsRepon.GetHocSinhForId(MaHocSinh);
            return View(hocSinh);
            }
            catch (Exception ex)
            {
                return RedirectToAction("SystemError", "Login");
            }
        }

        public ActionResult Partial_CT_HocPhi(string MaHocSinh, string thang)
        {
            try
            {

            PhieuThuHocPhiReponsitory ptRepon = new PhieuThuHocPhiReponsitory();
            DichVuNgoaiRePonsitory dvRepon = new DichVuNgoaiRePonsitory();
            HocSinhReponsitory hsRepon = new HocSinhReponsitory();
            var nhanvien = (NhanVien)Session["NhanVien"];
            DateTime ngaytaophieu;
            if (thang != null)
            {
                ngaytaophieu = DateTime.ParseExact(thang, "MM/yyyy", CultureInfo.InvariantCulture);
            }
            else
            {
                ngaytaophieu = DateTime.Now;
                thang = ngaytaophieu.ToString("MM/yyyy");
            }
            //lấy dịch vụ học sinh đăng ký trong tháng

            decimal tong1 = 0;
            decimal tong2=0;
            decimal tong3 = 0;
            decimal tong4 = 0;
            var listDichVuNgoai = dvRepon.getListDichVuNgoai_HocSinh(MaHocSinh, thang);

            foreach (var dvn in listDichVuNgoai)
            {
                tong3 += dvn.ChiPhi;
            }
            ViewData["tong3"] = tong3;

            //lấy học phí mặc định của tháng
            var listHocPhiThang = ptRepon.getHocPhiThang();

            foreach (var hp in listHocPhiThang)
            {
                tong1 += hp.ChiPhi;
            }
            ViewData["tong1"] = tong1;
            //lấy thông  tin điểm danh của học sinh trong tháng
            var pt = ptRepon.Get_Infor_TheoDoi(MaHocSinh, thang);
            if (pt == null)
            {
                pt = new Infor_TheoDoi();
            } 
            else
            {
                //công thức tính tiền học khi điểm danh--------VD:
                tong2 = HocPhiDefaul.TinhHocPhiTheoDoi(pt.SoNgayVang, pt.SoNgayAnSang, pt.SoNgayAnTrua);
            }
            ViewData["tong2"] = tong2;


            //lấy học phí đầu năm
            //

            var listHocPhiDauNam = ptRepon.getHocPhiDauNam();       
            foreach (var hp in listHocPhiDauNam)
            {
                tong4 += hp.ChiPhi;
            }
            string month = Convert.ToString(ngaytaophieu.Month);
            if (month!="1")
                {
                    tong4 = 0;
                }
                ViewData["month"] = month;
                ViewData["tong4"] = tong4;

            ViewData["tong"] = tong1 + tong2 + tong3 + tong4;
            // kiểm tra xem tồn tại phiếu thu chưa...
            if (pt == null)
            {
                pt = new Infor_TheoDoi();
                pt.MaHocSinh = MaHocSinh;
                pt.NgayTaoPhieu = thang;
                //pt.MaNhanVien = nhanvien.MaNhanVien;
                pt.SoNgayAnSang = 0;
                pt.SoNgayAnTrua = 0;
                pt.SoNgayVang = 0;
                //pt.ChiPhi = 0;
            }
            bool checkPhieuThu = false;
            //kiểm tra đóng học phí hay chưa(phieuthu)
            if (ptRepon.checkExistPhieuThu(MaHocSinh, thang))
            {
                checkPhieuThu = true;
            }
            ViewData["checkPhieuThu"] = checkPhieuThu;
                ViewModelPhieuThu viewModel = new ViewModelPhieuThu
                {
                    infor_phieuThu = pt,
                    listHocPhiThang = listHocPhiThang,
                    hocSinh = hsRepon.GetHocSinhForId(MaHocSinh),
                    listDichVuNgoai = listDichVuNgoai,
                    listHocPhiDauNam = listHocPhiDauNam,
                    tong1 = tong1,
                    tong2=tong2,
                    tong3=tong3,
                    tong4=tong4
                };
            //gửi thông tin viewModel qua bên controller thuphi
            TempData["viewModel"] = viewModel;
            ViewData["thang"] = thang;
            return PartialView(viewModel);
            }
            catch (Exception ex)
            {
                return RedirectToAction("SystemError", "Login");
            }
        }

        [HttpPost]
        public ActionResult ThuPhi()
        {
            var nhanvien = (NhanVien)Session["NhanVien"];
            ViewModelPhieuThu viewModel = TempData["viewModel"] as ViewModelPhieuThu;
            List<CT_PhieuThu_HocSinh> list_Ct_PhieuThu_HocSinh = new List<CT_PhieuThu_HocSinh>();
            CT_PhieuThu_HocSinh ct_pt_hs = null;
            PhieuThuHocPhiReponsitory phieuthuRepon = new PhieuThuHocPhiReponsitory();
            try
            {

                //kiểm tra tồn tại của phiếu thu
                if (!phieuthuRepon.checkExistPhieuThu(viewModel.infor_phieuThu.MaHocSinh, viewModel.infor_phieuThu.NgayTaoPhieu))
                {
                    //thêm mới phiếu thu từ thông tin điểm danh trong tháng (info_phieuthu)
                    var phieuThu = new PhieuThu();
                    phieuThu.MaHocSinh = viewModel.infor_phieuThu.MaHocSinh;
                    phieuThu.MaNhanVien = nhanvien.MaNhanVien;
                    phieuThu.NgayTaoPhieu = viewModel.infor_phieuThu.NgayTaoPhieu;

                    //bắt đầu thêm mới danh sách ct_Phieuthu_hocSinh
                    foreach (var HocPhiThang in viewModel.listHocPhiThang)
                    {
                        ct_pt_hs = new CT_PhieuThu_HocSinh();
                        ct_pt_hs.TenLoaiPhi = HocPhiThang.TenHocPhi;
                        ct_pt_hs.SoLuong = 1;
                        ct_pt_hs.ChiPhi = HocPhiThang.ChiPhi;
                        list_Ct_PhieuThu_HocSinh.Add(ct_pt_hs);
                    }
                    foreach (var dichVuNgoai in viewModel.listDichVuNgoai)
                    {
                        ct_pt_hs = new CT_PhieuThu_HocSinh();
                        ct_pt_hs.TenLoaiPhi = dichVuNgoai.TenDV;
                        ct_pt_hs.SoLuong = 1;
                        ct_pt_hs.ChiPhi = dichVuNgoai.ChiPhi;
                        list_Ct_PhieuThu_HocSinh.Add(ct_pt_hs);
                    }

                    ct_pt_hs = new CT_PhieuThu_HocSinh();
                    //lấy thông tin theo dõi, vang, ansang, antrua
                    ct_pt_hs.TenLoaiPhi = "DD_Vắng";
                    ct_pt_hs.SoLuong = viewModel.infor_phieuThu.SoNgayVang;
                    ct_pt_hs.ChiPhi = HocPhiDefaul.tienHoc1Buoi;//nhập chi phí vắng từng buổi//.....
                    list_Ct_PhieuThu_HocSinh.Add(ct_pt_hs);

                    ct_pt_hs = new CT_PhieuThu_HocSinh();
                    ct_pt_hs.TenLoaiPhi = "DD_Ăn sáng";
                    ct_pt_hs.SoLuong = viewModel.infor_phieuThu.SoNgayAnSang;
                    ct_pt_hs.ChiPhi = HocPhiDefaul.tienAnSang;//nhập chi phí ăn sáng từng buổi
                    list_Ct_PhieuThu_HocSinh.Add(ct_pt_hs);

                    ct_pt_hs = new CT_PhieuThu_HocSinh();
                    ct_pt_hs.TenLoaiPhi = "DD_Ăn trưa";
                    ct_pt_hs.SoLuong = viewModel.infor_phieuThu.SoNgayAnTrua;
                    ct_pt_hs.ChiPhi = HocPhiDefaul.tienAnTrua;//nhập chi phí ăn trưa từng buổi
                    list_Ct_PhieuThu_HocSinh.Add(ct_pt_hs);

                    PhieuThuHocPhiReponsitory ptHocPhiRepon = new PhieuThuHocPhiReponsitory();
                    ptHocPhiRepon.saveThuPhiHocSinh(phieuThu, list_Ct_PhieuThu_HocSinh);
                    //thực hiện lưu thông tin học phí
                    //thực hiện lưu bảng phieuThu

                    //thực hiện lưu bảng CT_phieuthu_hocSinh
                    return Json(new { success = true, responseText = "Thu mới thành công" }, JsonRequestBehavior.AllowGet);
                }
                return Json(new { success = false, responseText = "Đã thu!" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return RedirectToAction("SystemError", "Login");
            }
        }
        /// <summary>
        /// xuất hóa đơn sang excel
        /// </summary>
        public ActionResult ExportToExcel()
        {
            try
            {

QuanLyMamNon/QuanLyMamNon/Areas/Admin/Views/KeToan/DanhSachHocSinh.cshtml
@using QuanLyMamNon.Models
@*@using QuanLyMamNon.Reponsitory*@
@model QuanLyMamNon.Models.Dao.ViewModelDanhSachHS

@{
    ViewBag.Title = "DanhSachHocSinh";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12"><h1 class="page-header"><i class="fa fa-anchor fa-fw"></i>Trang chủ kế toán</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-12">
                            <i class="fa fa-th-list fa-2x">  Danh sách học sinh</i>
                        </div>
                    </div>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-4">
                            @using (Html.BeginForm("DanhSachHocSinh", "KeToan", FormMethod.Get, new { @class = "header-search-box", @style = "text-align:right" }))
                            {
                                <p>
                                </p><div class="form-inline">
                                    <div class="input-group">
                                        <select class="form-control" id="idd" name="groupLop">
                                            <option value="0">Tất cả</option>
                                            @foreach (var i in Model.listLop)
                                            {
                                                <option value="@i.MaLop">@i.TenLop</option>
                                            }
                                        </select>
                                        <span class="input-group-btn">
                                            <button class="btn btn-primary" type="submit">Hiển thị</button>
                                        </span>
                                    </div><!-- /input-group -->

                                </div>
                                <p></p>
                            }
                        </div>
                    </div>
                    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>
                                    Mã
                                </th>
                                <th>
                                    Học Và Tên
                                </th>
                                <th>
                                    Ngày Sinh
                                </th>
                                <th>
                                    Địa Chỉ
                                </th>
                                <th>
                                    Phụ Huynh
                                </th>
                                <th>
                                    Tel
                                </th>
                                <th>
                                    Email
                                </th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.listHocSinh)
                            {
                                <tr>
                                    <td>
                                        @item.MaHocSinh
                                    </td>
                                    <td>
                                        @item.Ten
                                    </td>
                                    <td>
                                        @item.NgaySinh.ToShortDateString()
                                    </td>
                                    <td>
                                        @item.DiaChi
                                    </td>
                                    <td>
                                        @item.TenPhuHuynh
                                    </td>
                                    <td>
                                        @item.Sdt
                                    </td>
                                    <td>
                                        @item.Email
                                    </td>
                                    <td>
                                        
                                        <a href="javascript:void(0);" class="btn btn-social-icon btn-bitbucket Details_HocSinh" data-id="@item.MaHocSinh"><i class="fa fa-info"></i></a>
                                        @Html.ActionLink(".", "HocPhiHocSinh", new { MaHocSinh = item.MaHocSinh, date = DateTime.Now.ToString("MM/yyyy") }, new {@class= "glyphicon glyphicon-bitcoin   " })
                                        
@*
    @{
        var reponse = new PhieuThuHocPhiReponsitory();

    }
    @if (!reponse.checkExistPhieuThu(item.MaHocSinh, "12/2017"))
    {
        @Html.ActionLink("Học phí", "HocPhiHocSinh", new { MaHocSinh = item.MaHocSinh, date = DateTime.Now.ToString("MM/yyyy") })
    }
    @if (reponse.checkExistPhieuThu(item.MaHocSinh, "12/2017"))
    {
        @Html.ActionLink("Học phí", "HocPhiHocSinh", new { MaHocSinh = item.MaHocSinh, date = DateTime.Now.ToString("MM/yyyy") },new {@style= "color:#ff0000" })
    }*@


                                        
                                       
                                       
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <div class="modal fade" id="myModal_detailsHocSinh" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog" style="width: 800px;">
                            <div class="modal-content" id="myModalContent">
                                <!-- Partial view Add,detail,update in here -->
                            </div>
                            <!-- /.modal-content -->
                        </div>
                        <!-- /.modal-dialog -->
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
</div>
<script>
    $('#idd option[value=@ViewBag.select]').attr('selected', 'selected');

    $(document).ready(function () {
        // do get details HocSinh
        $(".Details_HocSinh").click(function () {
            debugger;
            var detaisl_HocSinh_url = '@Url.Action("Detail", "HocSinh")';
            var $buttonClicked = $(this);
            var id = $buttonClicked.attr('data-id');
            var options = { "backdrop": "static", keyboard: true };
            $.ajax({
                type: "GET",
                url: detaisl_HocSinh_url,
                contentType: "application/json; charset=utf-8",
                data: { "Id": id },
                datatype: "json",
                success: function (data) {
                    debugger;
                    $('#myModalContent').html(data);
                    $('#myModal_detailsHocSinh').modal(options);
                    $('#myModal_detailsHocSinh').modal('show');
                },
                error: function () {
                    alert("Dynamic content load failed.");
                }
            });
        });
       
    });
</script>
<style>
    .image_link {
        color:red;
        background-image: url('../../img/monney.png');
    }
</style>

QuanLyMamNon/QuanLyMamNon/Areas/Admin/Views/KeToan/GenerateExcel.cshtml
@model QuanLyMamNon.Models.Dao.ViewModelPhieuThu
<h2>Ho va ten: @Model.hocSinh.Ten</h2>
<h2>Ngay lap phieu: @DateTime.Now.ToString()</h2>
<h2>Hoc Phi</h2>
<table>
    <tr>
        <th>Tên Loại Tiền</th>
        <th>Chi phi</th>
        <th>Tong 1</th>
    </tr>

    @foreach (var item in Model.listHocPhiThang)
    {
        <tr>
            <td>@item.TenHocPhi</td>
            <td>@item.ChiPhi vnd</td>
            <td>...</td>
        </tr>
    }
    <tr>
        <th></th>
        <th></th>
        <th>@Model.tong1</th>
    </tr>
</table>
<h2>Theo Doi</h2>
<table>
    <tr>
        <th>Ten Loai Tien</th>
        <th>Chi phi</th>
        <th>Tong 2</th>
    </tr>
    <tr>
        <td>So buoi nghi hoc: @Model.infor_phieuThu.SoNgayVang</td>
        <td>@Model.tienHoc1Buoi vnd</td>
        <td>...</td>
    </tr>
    <tr>
        <td>So ngay an sang: @Model.infor_phieuThu.SoNgayAnSang</td>
        <td>@Model.tienAnSang vnd</td>
        <td>...</td>
    </tr>
    <tr>
        <td>So ngay an trua: @Model.infor_phieuThu.SoNgayAnTrua</td>
        <td>@Model.tienAnTrua vnd</td>
        <td>...</td>
    </tr>
    <tr>
        <th></th>
        <th></th>
        <th>@Model.tong2</th>
    </tr>

</table>
<h2>Dich vu ngoai</h2>
<table>
    <tr>
        <th>Ten loai tien</th>
        <th>Chi phi</th>
        <th>Tong 3</th>
    </tr>
    @foreach (var item in Model.listDichVuNgoai)
    {
    <tr>
        <td> @item.TenDV</td>
        <td>@item.ChiPhi vnd </td>
        <td>@Model.tong3</td>
    </tr>        
    }
   
    <tr>
        <th></th>
        <th></th>
        <th>@Model.tong3</th>
    </tr>   
</table>
<h2>Tien Dau Nam</h2>
<table>
    <tr>
        <th>Ten loai tien</th>
        <th>Chi phi</th>
        <th>Tong 4</th>
    </tr>
    @foreach (var item in Model.listHocPhiDauNam)
    {
        <tr>
            <td> @item.TenHocPhi</td>
            <td>@item.ChiPhi vnd </td>
            <td>...</td>
        </tr>
    }

    <tr>
        <td></td>
        <td></td>
        <td>@Model.tong4</td>
    </tr>
</table>
<p>Tong hoc phi = (1)+(2)+(3)+(4) = @(Model.tong1+Model.tong2+Model.tong3+Model.tong4)</p>

QuanLyMamNon/QuanLyMamNon/Areas/Admin/Views/KeToan/HocPhiHocSinh.cshtml
@using QuanLyMamNon.Models
@model QuanLyMamNon.Models.HocSinh
@{
    ViewBag.Title = "HocPhiHocSinh";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><i class="fa fa-anchor fa-fw"></i>Trang chủ kế toán</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <p></p>
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Tính học phí học sinh @Model.Ten</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="row">
            <!-- /.col-lg-8 -->
            <div class="col-lg-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <i class="fa fa-bell fa-fw"></i> Thông tin chi tiết học sinh
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="panel panel-success">
                                    <div class="panel-heading">

                                        <i class="fa fa-comment fa-fw"></i> Thông tin học sinh
                                        <span class="pull-right text-muted small">
                                        </span>

                                    </div>
                                    <div class="list-group">                                       
                                        <a class="list-group-item">
                                            <i class="fa fa-child fa-fw"></i> Họ tên: @Model.Ten
                                            <i class="fa fa-calendar fa-fw"></i> Ngày sinh: @Model.NgaySinh.ToShortDateString()
                                            <i class="fa fa-leaf fa-fw"></i> Giới tính: @Model.GioiTinh
                                            <span class="pull-right text-muted small">
                                            </span>
                                        </a>
                                        <a class="list-group-item">
                                            <i class="fa fa-home fa-fw"></i> Địa chỉ: @Model.DiaChi
                                            <span class="pull-right text-muted small">
                                            </span>
                                        </a>
                                        <a class="list-group-item">
                                            <i class="fa fa-arrows-v fa-fw"></i> Chiều cao: @Model.ChieuCao cm<i class="fa fa-arrows-h fa-fw"></i> Cân Nặng: @Model.CanNang kg
                                            <span class="pull-right text-muted small">
                                            </span>
                                        </a>

                                        <a class="list-group-item">
                                            <i class="fa fa-shopping-cart fa-fw"></i> Tình trạng:@Model.TinhTrang
                                            <span class="pull-right text-muted small">
                                            </span>
                                        </a>
                                    </div>
                                </div>
                            </div>

                            <div class="col-lg-6">
                                <div class="panel panel-success">
                                    <div class="panel-heading">

                                        <i class="fa fa-comment fa-fw"></i> Thông tin phụ huynh
                                        <span class="pull-right text-muted small">
                                        </span>

                                    </div>
                                    <div class="list-group">
                                       
                                        <a class="list-group-item">
                                            <i class="fa fa-user fa-fw"></i> Họ tên: @Model.TenPhuHuynh
                                            <span class="pull-right text-muted small">
                                            </span>
                                        </a>
                                        <a class="list-group-item">
                                            <i class="fa fa-calendar fa-fw"></i> Ngày sinh: @Model.NgaySinhPhuHuynh.ToShortDateString()
                                            <span class="pull-right text-muted small">
                                            </span>
                                        </a>
                                        <a class="list-group-item">
                                            <i class="fa fa-phone fa-fw"></i> Tel: @Model.Sdt
                                            <span class="pull-right text-muted small">
                                            </span>
                                        </a>
                                        <a class="list-group-item">
                                            <i class="fa fa-envelope fa-fw"></i> Email: @Model.Email
                                            <span class="pull-right text-muted small">
                                            </span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-4 -->
        </div>
        <div id="resultHocPhi">
            <!-- /.row -->
            @Html.Action("Partial_CT_HocPhi", "KeToan")
        </div>

    </p>

QuanLyMamNon/QuanLyMamNon/Areas/Admin/Views/KeToan/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><i class="fa fa-anchor fa-fw"></i>Trang chủ kế toán</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
               <div class="col-lg-3 col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-group fa-5x"></i>
                        </div>
                    </div>
                </div>
                <a href="@Url.Action("DanhSachHocSinh","KeToan")">
                    <div class="panel-footer">
                        <span class="pull-left">DANH SÁCH HỌC SINH </span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-bar-chart-o fa-5x"></i>
                        </div>
                    </div>
                </div>
                <a href="@Url.Action("Index","KeToan")">
                    <div class="panel-footer">
                        <span class="pull-left">THỐNG KÊ THU CHI</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>
<!-- /#page-wrapper -->