QuanLyMamNon/QuanLyMamNon/Models/Entity/HocPhi.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace QuanLyMamNon.Models
{
    public class HocPhi
    {
        public string MaHocPhi { get; set; }
        public string TenHocPhi { get; set; }
        public decimal ChiPhi { get; set; }
        public string GhiChu { get; set; }
        public string LoaiHocPhi { get; set; }
        
    }
}

QuanLyMamNon/QuanLyMamNon/Areas/Admin/Controllers/HocPhiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuanLyMamNon.Models;
using QuanLyMamNon.Reponsitory;
using QuanLyMamNon.Models.Dao;

namespace QuanLyMamNon.Areas.Admin.Controllers
{
    [AuthorizeController]
    public class HocPhiController : Controller
    {
        HocPhiReponsitory hocphiRepon = new HocPhiReponsitory();
        
        public ActionResult Index()
        {try
            {

            string MaLoai = Request["listLoaiHocPhi"];
            var listHocPhi = new List<HocPhi>();
            var listLoaiHocPhi = hocphiRepon.getAllloaiHocPhi();
            var lstHS = new List<HocSinh>();
            if (string.IsNullOrEmpty(MaLoai) || MaLoai == "0")
            {
                MaLoai = "0";
                listHocPhi = hocphiRepon.getAllhocPhi();
            }
            else
            {
                listHocPhi = hocphiRepon.getHocPhiForIdLoaiHP(MaLoai);
            }
            ViewBag.select = MaLoai;
            
           
            var viewModel = new ViewModelHocPhi()
            {
                listHocPhi= listHocPhi,
                listLoaiHocPhi= listLoaiHocPhi
            };
            return View(viewModel);
            }
            catch (Exception ex)
            {
                return RedirectToAction("SystemError", "Login");
            }
        }
        //học phí
        public ActionResult AddHocPhi()
        {
            try
            {

            var listLoaiHocPhi = hocphiRepon.getAllloaiHocPhi();
            var viewModel = new ViewModelHocPhi()
            {
                listLoaiHocPhi= listLoaiHocPhi
            };
            return PartialView("Partial_AddHocPhi", viewModel); 
            }
            catch (Exception ex)
            {
                return RedirectToAction("SystemError", "Login");
            }           
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddHocPhi(HocPhi hocphi)
        {
            try
            {

            hocphiRepon.AddHocPhi(hocphi);
            return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return RedirectToAction("SystemError", "Login");
            }
        }
        public ActionResult UpdateHocPhi(string id)
        {
            try
            {

            var listLoaiHocPhi = hocphiRepon.getAllloaiHocPhi();
            var hocphi = hocphiRepon.getHocPhiForID(id);
            var viewModel = new ViewModelHocPhi()
            {
                hocphi=hocphi,
                listLoaiHocPhi = listLoaiHocPhi
            };
            return PartialView("Partial_UpdateHocPhi",viewModel);
            }
            catch (Exception ex)
            {
                return RedirectToAction("SystemError", "Login");
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateHocPhi(HocPhi hocphi)
        {
            try
            {

            hocphiRepon.UpdateHocPhi(hocphi);
            return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return RedirectToAction("SystemError", "Login");
            }
        }
        public JsonResult DeleteHocPhi(string id)
        {
            hocphiRepon.deleteHocPhi(id);
            return Json("ok", JsonRequestBehavior.AllowGet);
        }
        // Loại học phi 
        public ActionResult AddLoaiHocPhi()
        {
            return PartialView("Partial_AddLoaiHocPhi");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddLoaiHocPhi(LoaiHocPhi loaihocphi)
        {
            try
            {

            hocphiRepon.AddLoaiHocPhi(loaihocphi);
            return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return RedirectToAction("SystemError", "Login");
            }
        }
        public ActionResult UpdateLoaiHocPhi(string id)
        {
            try {

            var loaihocphi = hocphiRepon.getLoaiHocPhiForID(id);
            return PartialView("Partial_UpdateLoaiHocPhi",loaihocphi);
            }
            catch (Exception ex)
            {
                return RedirectToAction("SystemError", "Login");
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateLoaiHocPhi(LoaiHocPhi loaihocphi)
        {
            try
            {
            hocphiRepon.UpdateLoaiHocPhi(loaihocphi);
            return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                return RedirectToAction("SystemError", "Login");
            }
        }
       
        public JsonResult DeleteLoaiHocPhi(string id)
        {
            hocphiRepon.deleteLoaiHocPhi(id);
            return Json("ok", JsonRequestBehavior.AllowGet);
        }
    }
}

QuanLyMamNon/QuanLyMamNon/Areas/Admin/Views/HocPhi/Index.cshtml
@model QuanLyMamNon.Models.Dao.ViewModelHocPhi
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Quản lý học phí</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        <div class="col-lg-12" style="margin-top:20px">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-12">
                            <i class="fa fa-th-list fa-2x">  Danh sách loại học phí</i>
                        </div>
                    </div>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <button class="btn btn-primary add_LoaiHocPhi">
                                Thêm loại học phí
                            </button>
                            <p></p>
                        </div>
                    </div>
                    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>Mã loại</th>
                                <th>Tên loại</th>
                                <th>Ghi chú</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.listLoaiHocPhi)
                            {
                                <tr class="even gradeC">
                                    <td>
                                        @item.MaLoai
                                    </td>
                                    <td>
                                        @item.TenLoai
                                    </td>
                                    <td>
                                        @item.GhiChu
                                    </td>
                                    <td>
                                        <a href="javascript:void(0);" class="btn btn-social-icon btn-github Update_LoaiHocPhi" data-id="@item.MaLoai"><i class="fa fa-edit"></i></a>
                                        <a href="javascript:void(0);" class="btn btn-social-icon btn-pinterest Delete_LoaiHocPhi" data-id="@item.MaLoai"><i class="fa fa-trash-o"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <!-- /.table-responsive -->
                    <div class="modal fade" id="myModal_hocphi" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content" id="myModalContent">
                                <!-- Partial view Add,detail,update in here -->
                            </div>
                            <!-- /.modal-content -->
                        </div>
                        <!-- /.modal-dialog -->
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
        <div class="col-lg-12" style="margin-top:20px">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-12">
                            <i class="fa fa-th-list fa-2x">  Danh sách học phí</i>
                        </div>
                    </div>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-4">
                            <button class="btn btn-primary add_HocPhi">
                                Thêm học phí
                            </button>
                            <p></p>
                        </div>
                        <div class="col-lg-8">
                            @using (Html.BeginForm("Index", "HocPhi", FormMethod.Get, new { @class = "header-search-box", @style = "text-align:right" }))
                            {
                                <p>
                                </p>
                                <div class="form-inline">
                                    <div class="input-group">
                                        @Html.DropDownListFor(x => x.listLoaiHocPhi, new SelectList(Model.listLoaiHocPhi, "MaLoai", "TenLoai"), "Tất cả", new { @class = "form-control selectedValue" })
                                        <span class="input-group-btn">
                                            <button class="btn btn-primary" type="submit">Hiển thị</button>
                                        </span>
                                    </div><!-- /input-group -->

                                </div>
                                <p></p>
                            }
                        </div>
                    </div>
                    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example2">
                        <thead>
                            <tr>
                                <th>Mã học phí</th>
                                <th>Tên học phí</th>
                                <th>Chi phí</th>
                                <th>Ghi chú</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.listHocPhi)
                            {
                                <tr class="even gradeC">
                                    <td>
                                        @item.MaHocPhi
                                    </td>
                                    <td>
                                        @item.TenHocPhi
                                    </td>
                                    <td>
                                        @item.ChiPhi
                                    </td>
                                    <td>
                                        @item.GhiChu
                                    </td>
                                    <td>
                                        <a href="javascript:void(0);" class="btn btn-social-icon btn-github Update_HocPhi" data-id="@item.MaHocPhi"><i class="fa fa-edit"></i></a>
                                        <a href="javascript:void(0);" class="btn btn-social-icon btn-pinterest Delete_HocPhi" data-id="@item.MaHocPhi"><i class="fa fa-trash-o"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <!-- /.table-responsive -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
</div>

<script>
    //get selected in dropdown list when submit "hiển thị"
    $('.selectedValue option[value=@ViewBag.select]').attr('selected', 'selected');
    $(document).ready(function () {
        // do get Add LoaiHocPhi
        $(".add_LoaiHocPhi").click(function () {
            //debugger;
            var add_LoaiHocPhi_url = '@Url.Action("AddLoaiHocPhi", "HocPhi")';
            var $buttonClicked = $(this);
            var options = { "backdrop": "static", keyboard: true };
            $.ajax({
                type: "GET",
                url: add_LoaiHocPhi_url,
                contentType: "application/json; charset=utf-8",
                datatype: "json",
                success: function (data) {
                    //debugger;
                    $('#myModalContent').html(data);
                    $('#myModal_hocphi').modal(options);
                    $('#myModal_hocphi').modal('show');
                },
                error: function () {
                    alert("Dynamic content load failed.");
                }
            });
        });
        // do get edit LoaiHocPhi
        $(".Update_LoaiHocPhi").click(function () {
            //debugger;
            var update_LoaiHocPhi_url = '@Url.Action("UpdateLoaiHocPhi", "HocPhi")';
            var $buttonClicked = $(this);
            var id = $buttonClicked.attr('data-id');
            var options = { "backdrop": "static", keyboard: true };
            $.ajax({
                type: "GET",
                url: update_LoaiHocPhi_url,
                contentType: "application/json; charset=utf-8",
                data: { "Id": id },
                datatype: "json",
                success: function (data) {
                    //debugger;
                    $('#myModalContent').html(data);
                    $('#myModal_hocphi').modal(options);
                    $('#myModal_hocphi').modal('show');
                },
                error: function () {
                    alert("Dynamic content load failed.");
                }
            });
        });
        $(".Delete_LoaiHocPhi").click(function () {
            //debugger;
            var delete_LoaiHocPhi_url = '@Url.Action("DeleteLoaiHocPhi", "HocPhi")';
            var $buttonClicked = $(this);
            var id = $buttonClicked.attr('data-id');
            if (confirm("Do you want delete item?")) {
                $.ajax({
                    url: delete_LoaiHocPhi_url,
                    data: { Id: id },
                    type: 'POST',
                    dataType: 'json',
                    traditional: true,
                    success: function (data) {
                        alert("Delete success!");
                        location.reload();
                    },
                    error: function (xhr) {
                        alert('error');
                    }
                });
            } else
                return false;
        });
        //hoc phi
        $(".add_HocPhi").click(function () {
            debugger;
            var add_HocPhi_url = '@Url.Action("AddHocPhi", "HocPhi")';
            var $buttonClicked = $(this);
            var options = { "backdrop": "static", keyboard: true };
            $.ajax({
                type: "GET",
                url: add_HocPhi_url,
                contentType: "application/json; charset=utf-8",
                datatype: "json",
                success: function (data) {
                    debugger;
                    $('#myModalContent').html(data);
                    $('#myModal_hocphi').modal(options);
                    $('#myModal_hocphi').modal('show');
                },
                error: function () {
                    alert("Dynamic content load failed.");
                }
            });
        });
        // do get edit HocPhi
        $(".Update_HocPhi").click(function () {
            //debugger;
            var update_HocPhi_url = '@Url.Action("UpdateHocPhi", "HocPhi")';
            var $buttonClicked = $(this);
            var id = $buttonClicked.attr('data-id');
            var options = { "backdrop": "static", keyboard: true };
            $.ajax({
                type: "GET",
                url: update_HocPhi_url,
                contentType: "application/json; charset=utf-8",
                data: { "Id": id },
                datatype: "json",
                success: function (data) {
                    //debugger;
                    $('#myModalContent').html(data);
                    $('#myModal_hocphi').modal(options);
                    $('#myModal_hocphi').modal('show');
                },
                error: function () {
                    alert("Dynamic content load failed.");
                }
            });
        });
        $(".Delete_HocPhi").click(function () {
            //debugger;
            var delete_HocPhi_url = '@Url.Action("DeleteHocPhi", "HocPhi")';
            var $buttonClicked = $(this);
            var id = $buttonClicked.attr('data-id');
            if (confirm("Do you want delete item?")) {
                $.ajax({
                    url: delete_HocPhi_url,
                    data: { Id: id },
                    type: 'POST',
                    dataType: 'json',
                    traditional: true,
                    success: function (data) {
                        alert("Delete success!");
                        location.reload();
                    },
                    error: function (xhr) {
                        alert('error');
                    }
                });
            } else
                return false;
        });
    });
</script>

QuanLyMamNon/QuanLyMamNon/Areas/Admin/Views/HocPhi/Partial_AddHocPhi.cshtml
@model QuanLyMamNon.Models.Dao.ViewModelHocPhi

@using (Html.BeginForm("AddHocPhi", "HocPhi", FormMethod.Post, new { @role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Thêm mới</h4>
    </div>
        <div class="modal-body">
            <label>Tên học phí</label>(<i class="fa fa-star" style="color:red"></i>)
            <div class="form-group input-group input-group">
                <span class="input-group-addon">
                    <i class="fa fa-stack-overflow"></i>
                </span>
                @Html.TextBoxFor(x => x.hocphi.TenHocPhi, new { @class = "form-control", @data_error = "Please enter name field.", @placeholder = "Nhập tên...", @required = "required" })
            </div>
            <label>Chi phí</label>(<i class="fa fa-star" style="color:red"></i>)
            <div class="form-group input-group input-group">
                <span class="input-group-addon">
                    <i class="fa fa-money"></i>
                </span>
                @Html.TextBoxFor(x => x.hocphi.ChiPhi, new { @type="number",@class = "form-control", @data_error = "Please enter name field.", @placeholder = "Chi phí...", @required = "required" })
            </div>
            <label>Ghi chú</label>(<i class="fa fa-star" style="color:red"></i>)
            <div class="form-group input-group input-group">
                <span class="input-group-addon">
                    <i class="fa fa-comment"></i>
                </span>                
                @Html.TextAreaFor(x => x.hocphi.GhiChu, new { @class = "form-control", @placeholder = "Ghi chú..."  })
            </div>
            <label> Loại học phí</label>(<i class="fa fa-star" style="color:red"></i>)
            <div class="form-group input-group input-group">

                <span class="input-group-addon">
                    <i class="fa fa-stack-exchange"></i>
                </span>
                @Html.DropDownListFor(x => x.hocphi.LoaiHocPhi, new SelectList(Model.listLoaiHocPhi, "MaLoai", "TenLoai", 0), "None", new { @class = "form-control", @required = "required" })
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
            <button type="submit" class="btn btn-primary">Thêm mới</button>
        </div>
}

QuanLyMamNon/QuanLyMamNon/Areas/Admin/Views/HocPhi/Partial_AddLoaiHocPhi.cshtml
@model QuanLyMamNon.Models.LoaiHocPhi

@using (Html.BeginForm("AddLoaiHocPhi", "HocPhi", FormMethod.Post, new { @role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Thêm mới</h4>
    </div>
        <div class="modal-body">
            <label> Tên loại</label>(<i class="fa fa-star" style="color:red"></i>)
            <div class="form-group input-group input-group">
                <span class="input-group-addon">
                    <i class="fa fa-stack-exchange"></i>
                </span>
                @Html.TextBoxFor(x => x.TenLoai, new { @class = "form-control", @data_error = "Please enter name field.", @placeholder = "Nhập tên...", @required = "required" })
            </div>
            <label> Ghi chú</label>(<i class="fa fa-star" style="color:red"></i>)
            <div class="form-group input-group input-group">
                <span class="input-group-addon">
                    <i class="fa fa-comment"></i>
                </span>
                
                @Html.TextAreaFor(x => x.GhiChu, new { @class = "form-control", @placeholder = "Ghi chú..."  })

            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
            <button type="submit" class="btn btn-primary">Thêm mới</button>
        </div>
}

QuanLyMamNon/QuanLyMamNon/Areas/Admin/Views/HocPhi/Partial_UpdateHocPhi.cshtml
@model QuanLyMamNon.Models.Dao.ViewModelHocPhi
@using (Html.BeginForm("UpdateHocPhi", "HocPhi", FormMethod.Post, new { @role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h1 class="modal-title" id="myModalLabel">Update</h1>
    </div>
    <div class="modal-body">
        @Html.HiddenFor(x=>x.hocphi.MaHocPhi)
        <label>Tên học phí</label>(<i class="fa fa-star" style="color:red"></i>)
        <div class="form-group input-group input-group">
            <span class="input-group-addon">
                <i class="fa fa-stack-overflow"></i>
            </span>
            @Html.TextBoxFor(x => x.hocphi.TenHocPhi, new { @class = "form-control", @data_error = "Please enter name field.", @placeholder = "Nhập tên...", @required = "required" })
        </div>
        <label>Chi phí</label>(<i class="fa fa-star" style="color:red"></i>)
        <div class="form-group input-group input-group">
            <span class="input-group-addon">
                <i class="fa fa-money"></i>
            </span>
            @Html.TextBoxFor(x => x.hocphi.ChiPhi, new {  @class = "form-control", @data_error = "Please enter name field.", @placeholder = "Chi phí...", @required = "required" })
        </div>
        <label>Ghi chú</label>(<i class="fa fa-star" style="color:red"></i>)
        <div class="form-group input-group input-group">
            <span class="input-group-addon">
                <i class="fa fa-comment"></i>
            </span>
            @Html.TextAreaFor(x => x.hocphi.GhiChu, new { @class = "form-control", @placeholder = "Ghi chú..." })
        </div>
        <label> Loại học phí</label>(<i class="fa fa-star" style="color:red"></i>)
        <div class="form-group input-group input-group">
            <span class="input-group-addon">
                <i class="fa fa-stack-exchange"></i>
            </span>
            @Html.DropDownListFor(x => x.hocphi.LoaiHocPhi, new SelectList(Model.listLoaiHocPhi, "MaLoai", "TenLoai", 0), "None", new { @class = "form-control", @required = "required" })
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
        <button type="submit" class="btn btn-primary">Chỉnh sửa</button>
    </div>
}

QuanLyMamNon/QuanLyMamNon/Areas/Admin/Views/HocPhi/Partial_UpdateLoaiHocPhi.cshtml
@model QuanLyMamNon.Models.LoaiHocPhi
@using (Html.BeginForm("UpdateLoaiHocPhi", "HocPhi", FormMethod.Post, new { @role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h1 class="modal-title" id="myModalLabel">Update</h1>
    </div>
    <div class="modal-body">
        @Html.HiddenFor(x => x.MaLoai)
        <label> Tên loại</label>(<i class="fa fa-star" style="color:red"></i>)
        <div class="form-group input-group input-group">
            <span class="input-group-addon">
                <i class="fa fa-stack-exchange"></i>
            </span>
            @Html.TextBoxFor(x => x.TenLoai, new { @class = "form-control", @data_error = "Please enter name field.", @placeholder = "Nhập tên...", @required = "required" })
        </div>
        <label> Ghi chú</label>(<i class="fa fa-star" style="color:red"></i>)
        <div class="form-group input-group input-group">
            <span class="input-group-addon">
                <i class="fa fa-comment"></i>
            </span>

            @Html.TextAreaFor(x => x.GhiChu, new { @class = "form-control", @placeholder = "Ghi chú..." })

        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
        <button type="submit" class="btn btn-primary">Chỉnh sửa</button>
    </div>
}