QuanLyMamNon/QuanLyMamNon/Models/Entity/HocSinh.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace QuanLyMamNon.Models
{
    public class HocSinh
    {
        //public HocSinh()
        //{
            //this.CT_DichVu_HocSinh = new HashSet<CT_DichVu_HocSinh>();
            //this.CT_NgayTheoDoi = new HashSet<CT_NgayTheoDoi>();
            //this.PhieuThu = new HashSet<PhieuThu>();
        //}

        public string MaHocSinh { get; set; }
        public string Ten { get; set; }
        public DateTime NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string TinhTrang { get; set; }
        public int ChieuCao { get; set; }

        public int CanNang { get; set; }
        public string TenPhuHuynh { get; set; }
        public string SoCmt { get; set; }
        public string Sdt { get; set; }
        public string Email { get; set; }
        public DateTime NgaySinhPhuHuynh { get; set; }
        public string GhiChu { get; set; }
        public string MaLop { get; set; }
        public bool DoiTuongMTA { get; set; }
        public bool TrangThai { get; set; }

        //public virtual ICollection<CT_DichVu_HocSinh> CT_DichVu_HocSinh { get; set; }
        //public virtual ICollection<CT_NgayTheoDoi> CT_NgayTheoDoi { get; set; }
        //public virtual Lop Lop { get; set; }
        //public virtual ICollection<PhieuThu> PhieuThu { get; set; }
    }
}

QuanLyMamNon/QuanLyMamNon/Areas/Admin/Controllers/HocSinhController.cs
using QuanLyMamNon.Models;
using QuanLyMamNon.Models.Dao;
using QuanLyMamNon.Reponsitory;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.OleDb;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyMamNon.Areas.Admin.Controllers
{
    [AuthorizeController]
    public class HocSinhController : Controller
    {
        // GET: Home  CURD hocsinh
        public ActionResult Index()
        {
            try
            {
                HocSinhReponsitory hocSinhRepon = new HocSinhReponsitory();
                LopReponsitory lopRepon = new LopReponsitory();
                //danh sách học sinh chưa được phê duyệt
                var listHocSinhDis = hocSinhRepon.GetAllHocSinhDis();
                //danh sách học sinh đang hoạt động
                string MaLop = Request["listLop"];
                var listLop = lopRepon.getAllLop();
                var lstHS = new List<HocSinh>();
                if (string.IsNullOrEmpty(MaLop) || MaLop == "0")
                {
                    MaLop = "0";
                    lstHS = hocSinhRepon.GetAllHocSinh();
                }
                else
                {
                    lstHS = hocSinhRepon.GetHocSinhForIdLop(MaLop);
                }
                ViewBag.select = MaLop;
                var viewModel = new ViewModelDanhSachHS
                {
                    listLop = lopRepon.getAllLop(),
                    listHocSinh = lstHS,
                    listHocSinhDis = listHocSinhDis
                };
                return View(viewModel);
            }
            catch (Exception ex)
            {
                return RedirectToAction("SystemError", "Login");
            }

        }
        // GET: details hocsinh
        public ActionResult Detail(string id)
        {
            try
            {

                LopReponsitory lopRepon = new LopReponsitory();
                HocSinhReponsitory hocSinhRepon = new HocSinhReponsitory();
                var listLop = lopRepon.getAllLop();
                var hocsinh = hocSinhRepon.GetHocSinhForId(id);
                if (hocsinh.MaLop == null)
                {
                    ViewData["TenLop"] = "None";
                }
                else
                {
                    ViewData["TenLop"] = listLop.SingleOrDefault(x => x.MaLop == hocsinh.MaLop).TenLop.ToString();
                }
                ViewModelDanhSachHS viewModel = new ViewModelDanhSachHS
                {
                    hocsinh = hocsinh,
                    listLop = listLop
                };
                return PartialView("Partial_DetailHocSinh", viewModel);
            }
            catch (Exception ex)
            {
                return RedirectToAction("SystemError", "Login");
            }
        }
        // GET: add hocsinh
        public ActionResult Add()
        {
            try
            {

                LopReponsitory lopRepon = new LopReponsitory();
                var listLop = lopRepon.getAllLop();
                ViewModelDanhSachHS viewModel = new ViewModelDanhSachHS
                {
                    listLop = listLop
                };
                return PartialView("Partial_AddHocSinh", viewModel);
            }
            catch (Exception ex)
            {
                return RedirectToAction("SystemError", "Login");
            }
        }
        // POST: add hocsinh
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(HocSinh HocSinh)
        {
            try
            {

                HocSinhReponsitory hocSinhRepon = new HocSinhReponsitory();
                hocSinhRepon.AddHocSinh(HocSinh);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return RedirectToAction("SystemError", "Login");
            }
        }
        // GET: edit hocsinh
        public ActionResult Update(string id)
        {
            try
            {

                LopReponsitory lopRepon = new LopReponsitory();
                HocSinhReponsitory hocSinhRepon = new HocSinhReponsitory();
                var listLop = lopRepon.getAllLop();
                var hocsinh = hocSinhRepon.GetHocSinhForId(id);
                ViewModelDanhSachHS viewModel = new ViewModelDanhSachHS
                {
                    hocsinh = hocsinh,
                    listLop = listLop
                };
                return PartialView("Partial_UpdateHocSinh", viewModel);
            }
            catch (Exception ex)
            {
                return RedirectToAction("SystemError", "Login");
            }
        }
        // POST: edit hocsinh
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(HocSinh HocSinh)
        {
            try
            {

                HocSinhReponsitory hocSinhRepon = new HocSinhReponsitory();
                hocSinhRepon.UpdateHocSinh(HocSinh);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return RedirectToAction("SystemError", "Login");
            }
        }

        // POST: delete hocsinh
        [HttpPost]
        public JsonResult Delete(string id)
        {
            HocSinhReponsitory hocSinhRepon = new HocSinhReponsitory();
            hocSinhRepon.deleteHocSinh(id);
            return Json("ok", JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// import thông tin học sinh từ file excel
        /// </summary>
        /// <param name="postedFile"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult ImportFileHocSinh(HttpPostedFileBase postedFile)
        {
            try
            {
                HocSinhReponsitory hocSinhRepon = new HocSinhReponsitory();
                string filePath = string.Empty;
                if (postedFile != null)
                {
                    string path = Server.MapPath("~/Uploads/");
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }

                    filePath = path + Path.GetFileName(postedFile.FileName);
                    string extension = Path.GetExtension(postedFile.FileName);
                    postedFile.SaveAs(filePath);

                    string conString = string.Empty;
                    switch (extension)
                    {
                        case ".xls": //Excel 97-03.
                            conString = ConfigurationManager.ConnectionStrings["Excel03ConString"].ConnectionString;
                            break;
                        case ".xlsx": //Excel 07 and above.
                            conString = ConfigurationManager.ConnectionStrings["Excel07ConString"].ConnectionString;
                            break;
                    }
                    hocSinhRepon.ImportFileHocSinh(conString, filePath);
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return RedirectToAction("SystemError", "Login");
            }

        }

        /// <summary>
        /// đăng ký dịch vụ ngoài cho học sinh
        /// </summary>
        /// <returns></returns>
        public ActionResult DangKyDichVu(string id, string thang)
        {
            try
            {
                HocSinhReponsitory hocSinhRepon = new HocSinhReponsitory();
                var nhanvien = (NhanVien)Session["NhanVien"];
                DichVuNgoaiRePonsitory dvRepon = new DichVuNgoaiRePonsitory();
                NhanVienReponsitory nvRepon = new NhanVienReponsitory();

                //thực hiện kiểm tra ngày nhập vào
                DateTime dt = new DateTime();
                DateTime dtNow = new DateTime();

                dtNow = DateTime.Now;
                DateTime dtNowConvert = DateTime.ParseExact(dtNow.ToString("dd/MM/yyyy"), "dd/MM/yyyy", CultureInfo.InvariantCulture);
                if (thang == null)
                {
                    dt = DateTime.Now;
                    thang = dtNow.ToString("MM/yyyy");
                    ViewData["thang"] = thang;
                }
                else
                {
                    string dayNow = dtNow.Day.ToString();
                    if (dayNow.Count() == 1)
                    {
                        dayNow = "0" + dayNow;
                    }
                    dt = DateTime.ParseExact(dayNow + "/" + thang, "dd/MM/yyyy", CultureInfo.InvariantCulture);
                    ViewData["thang"] = thang;
                }

                var hocsinh = hocSinhRepon.GetHocSinhForId(id);
                var listDV = dvRepon.getAllDichVuNgoai();
                var listDV_HS = dvRepon.getListDichVuNgoai_HocSinh(id, thang);
                //check ngày xem kém ngày hiện tại và khong cho phép đang ký mới
                bool checkcompareDate = false;
                //nếu ngày đăng ký dịch vụ < ngày hiện tại, thông báo không cho đăng ký mới
                if (DateTime.Compare(dt, dtNowConvert) < 0)
                {
                    ViewData["compareDate"] = thang;
                    checkcompareDate = true;
                }
                ViewData["compareDate"] = checkcompareDate;
                //kiểm tra đã đăng ký dịch vụ tháng này chưa
                bool checkExist = false;
                if (listDV_HS.Count() != 0)
                {
                    checkExist = true;
                }
                ViewData["checkExist"] = checkExist;

                var viewModel = new ViewModelDangKyDV_HS
                {
                    hocsinh = hocsinh,
                    nhanvien = nhanvien,
                    listDV = listDV,
                    listDV_HS = listDV_HS
                };

QuanLyMamNon/QuanLyMamNon/Areas/Admin/Views/HocSinh/Partial_AddHocSinh.cshtml
@using QuanLyMamNon.Models
@model QuanLyMamNon.Models.Dao.ViewModelDanhSachHS

@using (Html.BeginForm("Add", "HocSinh", FormMethod.Post, new { @role = "form", @data_toggle = "validator" }))
{
    @Html.AntiForgeryToken()
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Thêm mới</h4>
    </div>
    <div class="modal-body">
        <div class="panel panel-primary">
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                Thông tin học sinh
                            </div>
                            <div class="panel-body">
                                <label>Họ và tên</label>(<i class="fa fa-star" style="color:red"></i>)
                                <div class="form-group input-group">
                                    <span class="input-group-addon">
                                        <i class="fa fa-child"></i>
                                    </span>
                                    @Html.TextBoxFor(x => x.hocsinh.Ten, new { @class = "form-control", @data_error = "Please enter name field.", @placeholder = "Nhập tên...", @required = "required" })
                                </div>
                                <label>Ngày sinh</label>(<i class="fa fa-star" style="color:red"></i>)
                                <div class="form-group input-group">
                                    <span class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </span>
                                    @Html.TextBoxFor(x => x.hocsinh.NgaySinh, new { @type = "date", @class = "form-control", @placeholder = "Ngày sinh...", @required = "required" })
                                </div>
                                <label>Giới tính</label>(<i class="fa fa-star" style="color:red"></i>)
                                <div class="form-group input-group">
                                    <span class="input-group-addon">
                                        <i class="fa fa-leaf"></i>
                                    </span>
                                    @Html.DropDownListFor(x => x.hocsinh.GioiTinh, new SelectList(new List<string> { "Nam", "Nữ" }, 0), "--Chọn giới tính--", new { @class = "form-control", @placeholder = "Giới tính...", @required = "required" })
                                </div>
                                <label>Địa chỉ</label>(<i class="fa fa-star" style="color:red"></i>)
                                <div class="form-group input-group">
                                    <span class="input-group-addon">
                                        <i class="fa fa-home"></i>
                                    </span>
                                    @Html.TextBoxFor(x => x.hocsinh.DiaChi, new { @class = "form-control", @placeholder = "Địa chỉ...", @required = "required" })
                                </div>
                                <label>Chiều cao, cân nặng</label>
                                <div class="form-group input-group">
                                    <span class="input-group-addon">
                                        <i class="fa fa-arrows-v"></i>
                                    </span>
                                    @Html.TextBoxFor(x => x.hocsinh.ChieuCao, new { @class = "form-control", @pattern = "([0-9]{1,3})", @type = "number", @placeholder = "Chiều cao..." })
                                    <span class="input-group-addon">.cm</span>
                                    <span class="input-group-addon">
                                        <i class="fa fa-arrows-h"></i>
                                    </span>
                                    @Html.TextBoxFor(x => x.hocsinh.CanNang, new { @type = "number", @class = "form-control", @placeholder = "Cân nặng..." })
                                    <span class="input-group-addon">.kg</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                Thông tin phụ huynh
                            </div>
                            <div class="panel-body">
                                <label>Họ và tên</label>(<i class="fa fa-star" style="color:red"></i>)
                                <div class="form-group input-group">
                                    <span class="input-group-addon">
                                        <i class="fa fa-user"></i>
                                    </span>
                                    @Html.TextBoxFor(x => x.hocsinh.TenPhuHuynh, new { @class = "form-control", @data_error = "Please enter name field.", @placeholder = "Nhập tên...", @required = "required" })
                                </div>
                                <label>Ngày sinh</label>(<i class="fa fa-star" style="color:red"></i>)
                                <div class="form-group input-group">
                                    <span class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </span>
                                    @Html.TextBoxFor(x => x.hocsinh.NgaySinhPhuHuynh, new { @type = "date", @class = "form-control", @placeholder = "Ngày sinh...", @required = "required" })
                                </div>
                                <label>Số chứng minh thư</label>
                                <div class="form-group input-group">
                                    <span class="input-group-addon">
                                        <i class="fa fa-credit-card"></i>
                                    </span>
                                    @Html.TextBoxFor(x => x.hocsinh.SoCmt, new { @class = "form-control", @placeholder = "Số chứng minh thư..." })
                                </div>
                                <label>Số điện thoại</label>(<i class="fa fa-star" style="color:red"></i>)
                                <div class="form-group input-group">
                                    <span class="input-group-addon">
                                        <i class="fa fa-phone"></i>
                                    </span>
                                    @Html.TextBoxFor(x => x.hocsinh.Sdt, new { @class = "form-control", @type = "tel", @pattern = "([0-9+ _-]{9,15})", @required = "required", @placeholder = "Số điện thoại... (ký tự số từ 0-9, độ dài 9-15 ký tự(ví dụ '01676983088')" })
                                </div>
                                <label>Email</label>(<i class="fa fa-star" style="color:red"></i>)
                                <div class="form-group input-group">
                                    <span class="input-group-addon">
                                        <i class="fa fa-envelope"></i>
                                    </span>
                                    @Html.TextBoxFor(x => x.hocsinh.Email, new { @class = "form-control", @type = "email", @data_error = "Bruh, that email address is invalid", @required = "required", @placeholder = "john@doe.com" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group input-group">
                            <label>Tình trạng hoạt động </label>
                            @Html.CheckBoxFor(x => x.hocsinh.TrangThai, new { @class = "form-control checkTrangThai" })

                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group input-group">
                            <label>Là đối tượn con MTA</label>
                            @Html.CheckBoxFor(x => x.hocsinh.DoiTuongMTA, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="col-lg-4 showHide">
                        <div class="form-group input-group DropListLop">
                            <label>Chọn lớp học</label>
                            @Html.DropDownListFor(x => x.hocsinh.MaLop, new SelectList(Model.listLop, "MaLop", "TenLop", 0), "None", new { @class = "form-control dropdownLop", @required = "required" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <label>Ghi chú</label>
                        <div class="form-group input-group">
                            <span class="input-group-addon">
                                <i class="fa fa-comments"></i>
                            </span>
                            @Html.TextBoxFor(x => x.hocsinh.GhiChu, new { @class = "form-control", @placeholder = "Ghi chú..." })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
                <button type="submit" class="btn btn-primary">Thêm mới</button>
            </div>
            }
            <script>
                $(".showHide").hide();
                $(document).ready(function () {
                    $(".checkTrangThai").click(function () {
                        if ($(this).is(":checked")) {
                            $(".showHide").show();
                        } else {
                            $(".dropdownLop").removeAttr("required");
                            $(".showHide").hide();
                        }
                    });
                })
            </script>

QuanLyMamNon/QuanLyMamNon/Areas/Admin/Views/HocSinh/Partial_DangKyDichVu.cshtml
@model QuanLyMamNon.Models.Dao.ViewModelDangKyDV_HS
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Thông tin học sinh và môn học</h4>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Môn học năng khiếu đã đăng ký của bé @Model.hocsinh.Ten
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="col-lg-12">
                        <div class="form-group" id="sandbox-container">
                            <input type="text" value="@ViewData["thang"].ToString()" name="date" class="form-control datetime" placeholder="Chọn tháng....">
                        </div>
                    </div>
                    <div class="table-responsive table-bordered">
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>Mã môn học</th>
                                    <th>Tên môn học</th>
                                    <th>Chi phí</th>
                                    <th>Ghi chú</th>
                                    <th>@*Người đăng ký*@</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.listDV_HS)
                                {
                                    <tr>
                                        <td>@item.MaDichVu</td>
                                        <td>@item.TenDV</td>
                                        <td>@item.ChiPhi</td>
                                        <td>@item.GhiChu</td>
                                        @*<td>Kế toán Hùng</td>*@
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <div class="alert alert-danger" id="mess_ChuaDK">
                        Chưa đăng ký.
                    </div>
                    <div class="alert alert-info" id="mess_DaDK">
                        Đã đăng ký.
                    </div>
                    <div class="alert alert-danger" id="mess_KhongDuocDK">
                        Không được phép đăng ký.
                    </div>
                    
                    <p></p>
                    <button type="button" data-toggle="collapse" data-target="#demo" class="btn btn-default" id="btnDangKy">Đăng ký ngay</button>
                    <!-- /.table-responsive -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <div class="col-lg-12 collapse" id="demo">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Đăng ký thêm
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <label>Chọn môn</label>
                    <div class="form-group">
                        @foreach (var item in Model.listDV)
                        {
                            <label class="checkbox-inline">
                                <input type="checkbox" class="test" value="@item.MaDichVu">@item.TenDV
                                @*<input type="checkbox" class="test" value="@item.MaDichVu" @foreach (var i in Model.listDV_HS) { if (i.MaDichVu == item.MaDichVu) { @: checked
                                    } }>@item.TenDV*@
                            </label>
                        }
                    </div>                    
                    <div class="alert alert-danger" id="mess_ChuaChon">
                        Bạn chưa chưa chọn dịch vụ!
                    </div>
                    <button type="button" class="btn btn-primary submit">Đăng ký mới</button>
                    <!-- /.table-responsive -->
                </div>
                <div class="modal fade" id="myModal_detailsHocSinh" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog" style="width: 800px;">
                        <div class="modal-content" id="myModalContent">
                            <!-- Partial view Add,detail,update in here -->
                        </div>
                        <!-- /.modal-content -->
                    </div>
                    <!-- /.modal-dialog -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
</div>
<script>
    $("#mess_ChuaDK").hide();
    $("#mess_DaDK").hide();
    $("#mess_KhongDuocDK").hide();
    $("#btnDangKy").hide();
    $("#mess_ChuaChon").hide();
    
    if( @ViewData["compareDate"].ToString().ToLower() == true ) {
        $("#btnDangKy").hide();
        $("#mess_KhongDuocDK").show();
    }else{
        if( @ViewData["checkExist"].ToString().ToLower() == true ) {
            $("#btnDangKy").hide();
            $("#mess_DaDK").show();
        }else{
            $("#btnDangKy").show();
            $("#mess_ChuaDK").show();
        }
    }

    
    //hieent thị thông tin  đang ký dịch vụ của học sinh
    $(function() {
        $('.datetime').datepicker({
            format: "mm/yyyy",
            minViewMode: 1,
            todayBtn: "linked",
            calendarWeeks: true,
            autoclose: true,
            onSelect: function() {
                $(this).change();
            }
        }).on("change", function() {
            debugger;
            var date = $(this).val();
            var MaHocSinh=@Model.hocsinh.MaHocSinh;

            if (date && date != '') {
                debugger;
                $.ajax({
                    url: '@Url.Action("DangKyDichVu")',
                    type: 'GET',
                    cache: false,
                    data: {  'id':MaHocSinh,
                        'thang': date
                    },
                    success: function (data) {
                        $('#myModalContent').html(data);
                        //$('#myModal_detailsHocSinh').modal(options);
                        $('#myModal_detailsHocSinh').modal('show');
                    },
                    error: function () {
                        alert("Dynamic content load failed.");
                    }
                });
            }
        });
    });
    //hiển thị đăng ký dịch vụ mới
    $(function() {
        $('.datetime').datepicker({
            format: "mm/yyyy",
            minViewMode: 1,
            todayBtn: "linked",
            calendarWeeks: true,
            autoclose: true,
            onSelect: function() {
                $(this).change();
            }
        }).on("change", function() {
            debugger;
            var date = $(this).val();
            var MaHocSinh=@Model.hocsinh.MaHocSinh;

            if (date && date != '') {
                debugger;
                $.ajax({
                    url: '@Url.Action("DangKyDichVu")',
                    type: 'GET',
                    cache: false,
                    data: {  'id':MaHocSinh,
                        'thang': date
                    },
                    success: function (data) {
                        $('#myModalContent').html(data);
                        //$('#myModal_detailsHocSinh').modal(options);
                        $('#myModal_detailsHocSinh').modal('show');
                    },
                    error: function () {
                        alert("Dynamic content load failed.");
                    }
                });
            }
        });
    });
    //thục hiện lưu
    $(function() {
        $(".submit").click(function(){
            var maHocSinh = @Model.hocsinh.MaHocSinh;
            var thang=$('.datetime').val();
            var listMaDV = [];
            $('.test:checked').each(function () {
                listMaDV.push($(this).val());
            });

            if (listMaDV == "") {
                $("#mess_ChuaChon").show();
            }
            else {
                debugger;
                $.ajax({                        
                    url: '@Url.Action("SaveDV_HS", "HocSinh")',
                    data: { listMaDV: listMaDV, maHocSinh: maHocSinh, thangdk: thang },
                    type: 'POST',
                    dataType: 'json',
                    traditional: true,
                    success: function (response) {
                        if (response != null && response.success) {
                            alert(response.responseText);
                            location.reload();
                        } else {
                            // DoSomethingElse()
                            alert(response.responseText);
                        }                          
                    },
                    error: function (response) {
                        alert("error!");  // 
                    }
                });
            }
        });
    })
</script>