QuanLyMamNon/QuanLyMamNon/Models/Entity/DichVuNgoai.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace QuanLyMamNon.Models
{
    public class DichVuNgoai
    {
        //public DichVuNgoai()
        //{
        //    this.CT_DichVu_HocSinh = new HashSet<CT_DichVu_HocSinh>();
        //}

        public string MaDichVu { get; set; }
        public string TenDV { get; set; }
        public decimal ChiPhi { get; set; }
        public string GhiChu { get; set; }

        //public virtual ICollection<CT_DichVu_HocSinh> CT_DichVu_HocSinh { get; set; }
    }
}

QuanLyMamNon/QuanLyMamNon/Areas/Admin/Controllers/DichVuNgoaiController.cs
using QuanLyMamNon.Models;
using QuanLyMamNon.Reponsitory;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyMamNon.Areas.Admin.Controllers
{
    [AuthorizeController]
    public class DichVuNgoaiController : Controller
    {
        DichVuNgoaiRePonsitory hocphiRepon = new DichVuNgoaiRePonsitory();
        // GET: Home  CURD 
        public ActionResult Index()
        {
            try
            {

                var listDichVuNgoai = hocphiRepon.getAllDichVuNgoai();
                return View(listDichVuNgoai);
            }
            catch (Exception ex)
            {
                return RedirectToAction("SystemError", "Login");
            }
        }

        // GET: add 
        public ActionResult Add()
        {
            try
            {

                return PartialView("Partial_AddDichVuNgoai");
            }
            catch (Exception ex)
            {
                return RedirectToAction("SystemError", "Login");
            }
        }
        // POST: add 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(DichVuNgoai dichvungoai)
        {
            try
            {

                hocphiRepon.AddDichVuNgoai(dichvungoai);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return RedirectToAction("SystemError", "Login");
            }
        }
        // GET: edit 
        public ActionResult Update(string id)
        {
            try
            {

                var DichVuNgoai = hocphiRepon.getDichVuNgoaiForId(id);
                return PartialView("Partial_UpdateDichVuNgoai", DichVuNgoai);
            }
            catch (Exception ex)
            {
                return RedirectToAction("SystemError", "Login");
            }
        }
        // POST: edit 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(DichVuNgoai dichvungoai)
        {
            try
            {

                hocphiRepon.UpdateDichVuNgoai(dichvungoai);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return RedirectToAction("SystemError", "Login");
            }
        }
        // POST: delete DichVuNgoai
        [HttpPost]
        public JsonResult Delete(string id)
        {
            hocphiRepon.deleteDichVuNgoai(id);
            return Json("ok", JsonRequestBehavior.AllowGet);
        }
    }
}

QuanLyMamNon/QuanLyMamNon/Areas/Admin/Views/DichVuNgoai/Index.cshtml
@using QuanLyMamNon.Models
@model List<QuanLyMamNon.Models.DichVuNgoai>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Quản lý dịch vụ ngoài</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        <div class="col-lg-12" style="margin-top:20px">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-12">
                            <i class="fa fa-th-list fa-2x">  Danh sách dịch vụ ngoài</i>
                        </div>
                    </div>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <button class="btn btn-primary add_DichVuNgoai">
                                Thêm dịch vụ
                            </button>
                            <p></p>
                        </div>
                    </div>
                    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>Mã dịch vụ</th>
                                <th>Tên dịch vụ</th>
                                <th>Chi phí</th>
                                <th>Ghi chú</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr class="even gradeC">
                                    <td>
                                        @item.MaDichVu
                                    </td>
                                    <td>
                                        @item.TenDV
                                    </td>
                                    <td>
                                        @item.ChiPhi
                                    </td>
                                    <td>
                                        @item.GhiChu
                                    </td>
                                    <td>
                                        
                                        <a href="javascript:void(0);" class="btn btn-social-icon btn-github Update_DichVuNgoai" data-id="@item.MaDichVu"><i class="fa fa-edit"></i></a>
                                        <a href="javascript:void(0);" class="btn btn-social-icon btn-pinterest Delete_DichVuNgoai" data-id="@item.MaDichVu"><i class="fa fa-trash-o"></i></a>                                        
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <!-- /.table-responsive -->
                    <div class="modal fade" id="myModal_detailsDichVuNgoai" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content" id="myModalContent">
                                <!-- Partial view Add,detail,update in here -->
                            </div>
                            <!-- /.modal-content -->
                        </div>
                        <!-- /.modal-dialog -->
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
</div>

<script>
    $(document).ready(function () {
        // do get Add DichVuNgoai
        $(".add_DichVuNgoai").click(function () {
            //debugger;
            var add_DichVuNgoai_url = '@Url.Action("Add", "DichVuNgoai")';
            var $buttonClicked = $(this);
            var options = { "backdrop": "static", keyboard: true };
            $.ajax({
                type: "GET",
                url: add_DichVuNgoai_url,
                contentType: "application/json; charset=utf-8",
                datatype: "json",
                success: function (data) {
                    //debugger;
                    $('#myModalContent').html(data);
                    $('#myModal_detailsDichVuNgoai').modal(options);
                    $('#myModal_detailsDichVuNgoai').modal('show');
                },
                error: function () {
                    alert("Dynamic content load failed.");
                }
            });
        });
        // do get edit DichVuNgoai
        $(".Update_DichVuNgoai").click(function () {
            //debugger;
            var update_DichVuNgoai_url = '@Url.Action("Update", "DichVuNgoai")';
            var $buttonClicked = $(this);
            var id = $buttonClicked.attr('data-id');
            var options = { "backdrop": "static", keyboard: true };
            $.ajax({
                type: "GET",
                url: update_DichVuNgoai_url,
                contentType: "application/json; charset=utf-8",
                data: { "Id": id },
                datatype: "json",
                success: function (data) {
                    //debugger;
                    $('#myModalContent').html(data);
                    $('#myModal_detailsDichVuNgoai').modal(options);
                    $('#myModal_detailsDichVuNgoai').modal('show');
                },
                error: function () {
                    alert("Dynamic content load failed.");
                }
            });
        });
        $(".Delete_DichVuNgoai").click(function () {
            //debugger;
            var delete_DichVuNgoai_url = '@Url.Action("Delete", "DichVuNgoai")';
            var $buttonClicked = $(this);
            var id = $buttonClicked.attr('data-id');
            if (confirm("Do you want delete item?")) {
                $.ajax({
                url: delete_DichVuNgoai_url,
                data: { Id: id },
                type: 'POST',
                dataType: 'json',
                traditional: true,
                success: function (data) {
                    alert("Delete success!");
                    location.reload();
                },
                error: function (xhr) {
                    alert('error');
                }
            });
        } else
                return false;
    });
    });
</script>

QuanLyMamNon/QuanLyMamNon/Areas/Admin/Views/DichVuNgoai/Partial_AddDichVuNgoai.cshtml
@model QuanLyMamNon.Models.DichVuNgoai

@using (Html.BeginForm("Add", "DichVuNgoai", FormMethod.Post, new { @role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Thêm mới</h4>
    </div>
        <div class="modal-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <label> Tên dịch vụ</label>(<i class="fa fa-star" style="color:red"></i>)
            <div class="form-group input-group input-group">
                <span class="input-group-addon">
                    <i class="fa fa-cutlery"></i>
                </span>
                @Html.TextBoxFor(x => x.TenDV, new { @class = "form-control", @data_error = "Please enter name field.", @placeholder = "Nhập tên dịch vu...", @required = "required" })
            </div>
            <label> Chi phí</label>(<i class="fa fa-star" style="color:red"></i>)
            <div class="form-group input-group input-group">
                <span class="input-group-addon">
                    <i class="fa fa-money"></i>
                </span>
                @Html.TextBoxFor(x => x.ChiPhi, new { @type="number", @class = "form-control", @placeholder = "Chi phí...", @required = "required" })
            </div>
            <label> Ghi chú</label>(<i class="fa fa-star" style="color:red"></i>)
            <div class="form-group input-group input-group">
                <span class="input-group-addon">
                    <i class="fa fa-comment"></i>
                </span>
                
                @Html.TextAreaFor(x => x.GhiChu, new { @class = "form-control", @placeholder = "Ghi chú..."  })

            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
            <button type="submit" class="btn btn-primary">Thêm mới</button>
        </div>
}

QuanLyMamNon/QuanLyMamNon/Areas/Admin/Views/DichVuNgoai/Partial_UpdateDichVuNgoai.cshtml
@model QuanLyMamNon.Models.DichVuNgoai
@using (Html.BeginForm("Update", "DichVuNgoai", FormMethod.Post, new { @role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h1 class="modal-title" id="myModalLabel">Update</h1>
    </div>
    <div class="modal-body">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(x=>x.MaDichVu)
        <label> Tên dịch vụ</label>(<i class="fa fa-star" style="color:red"></i>)
        <div class="form-group input-group input-group">
            <span class="input-group-addon">
                <i class="fa fa-cutlery"></i>
            </span>
            @Html.TextBoxFor(x => x.TenDV, new { @class = "form-control", @data_error = "Please enter name field.", @placeholder = "Nhập tên dịch vu...", @required = "required" })
        </div>
        <label> Chi phí</label>(<i class="fa fa-star" style="color:red"></i>)
        <div class="form-group input-group input-group">
            <span class="input-group-addon">
                <i class="fa fa-money"></i>
            </span>
            @Html.TextBoxFor(x => x.ChiPhi, new { @class = "form-control", @placeholder = "Chi phí...", @required = "required"    })
        </div>
        <label> Ghi chú</label>(<i class="fa fa-star" style="color:red"></i>)
        <div class="form-group input-group input-group">
            <span class="input-group-addon">
                <i class="fa fa-comment"></i>
            </span>

            @Html.TextAreaFor(x => x.GhiChu, new { @class = "form-control", @placeholder = "Ghi chú..." })

        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
        <button type="submit" class="btn btn-primary">Chỉnh sửa</button>
    </div>
}